import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { apiClient } from "../../api/Api";
import { AuthHeader } from "../../components/auth-header/AuthHeader";
import { Button } from "../../components/button/Button";
import { saveTenantId } from "../../lib/session";
import { getDashboardData } from "../../services/dashboardService";
import styles from "./MultiFactorPage.module.css";

type MagicLoginQueryResponse = {
  two_factor?: string;
};

function normalizeMagicLoginQuery(query: string): string {
  const raw = query.startsWith("?") ? query.slice(1) : query;
  const parsed = new URLSearchParams(raw);
  const normalized = new URLSearchParams();
  for (const [key, value] of parsed.entries()) {
    const normalizedKey = key.startsWith("amp;") ? key.slice(4) : key;
    normalized.append(normalizedKey, value);
  }
  return normalized.toString();
}

function getTenantIdFromAuthenticationStatus(data: any): string | number | null {
  if (!data || typeof data !== "object") return null;
  if (data.tenant_id !== undefined && data.tenant_id !== null && String(data.tenant_id).trim() !== "") {
    return data.tenant_id;
  }
  if (data.tenant?.id !== undefined && data.tenant?.id !== null && String(data.tenant.id).trim() !== "") {
    return data.tenant.id;
  }
  if (data.user?.tenant_id !== undefined && data.user?.tenant_id !== null && String(data.user.tenant_id).trim() !== "") {
    return data.user.tenant_id;
  }
  return null;
}

export function MultiFactorPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const api = useMemo(() => apiClient, []);
  const tokenFromState = (location.state as { twoFactorToken?: string } | null)?.twoFactorToken ?? "";
  const [resolvedTwoFactorToken, setResolvedTwoFactorToken] = useState(tokenFromState);
  const [isResolvingToken, setIsResolvingToken] = useState(
    tokenFromState.trim().length === 0 && location.search.trim().length > 0,
  );
  const otpInputRefs = useRef<Array<HTMLInputElement | null>>([]);

  const [otpDigits, setOtpDigits] = useState<string[]>(Array(6).fill(""));
  const [error, setError] = useState("");
  const [isProceeding, setIsProceeding] = useState(false);

  const otpCode = otpDigits.join("");
  const canProceed = otpCode.length === 6 && resolvedTwoFactorToken.trim().length > 0 && !isResolvingToken;

  useEffect(() => {
    if (tokenFromState.trim().length > 0) {
      console.log("[MultiFactor] Using twoFactorToken from route state.");
      setResolvedTwoFactorToken(tokenFromState);
      setIsResolvingToken(false);
      return;
    }

    const query = normalizeMagicLoginQuery(location.search);
    if (!query) {
      console.warn("[MultiFactor] Missing query params on magic-login route.", {
        frontendRoute: `${window.location.pathname}${window.location.search}`,
      });
      navigate("/onboarding/request-magic-link", {
        replace: true,
        state: { error: "Missing magic link parameters. Please request a new email link." },
      });
      return;
    }

    let isMounted = true;
    setIsResolvingToken(true);
    void (async () => {
      const endpoint = `/api/magic-login?${query}`;
      console.log("[MultiFactor] Verifying magic login link...", {
        frontendRoute: `${window.location.pathname}${window.location.search}`,
        backendEndpoint: endpoint,
        params: Object.fromEntries(new URLSearchParams(query).entries()),
      });
      try {
        const response = await api.get<MagicLoginQueryResponse>(endpoint);
        console.log("[MultiFactor] Magic link verification response:", response);
        const token = response?.two_factor?.trim();
        if (!token) throw new Error("Missing two_factor token.");
        if (!isMounted) return;
        console.log("[MultiFactor] two_factor token resolved.");
        setResolvedTwoFactorToken(token);
      } catch (error) {
        if (!isMounted) return;
        console.error("[MultiFactor] Magic link verification failed.", {
          backendEndpoint: endpoint,
          error,
        });
        navigate("/onboarding/request-magic-link", {
          replace: true,
          state: { error: "Could not verify magic link. Please request a new email link." },
        });
      } finally {
        if (isMounted) setIsResolvingToken(false);
      }
    })();

    return () => {
      isMounted = false;
    };
  }, [api, location.search, navigate, tokenFromState]);

  return (
    <div className={styles.page}>
      <AuthHeader variant="dashboard" userInitial="J" />

      <main className={styles.main}>
        <div className={styles.intro}>
          <h1 className={styles.title}>Authenticate to continue</h1>
          <p className={styles.subtitle}>
            Enter a verification code generated by your two-factor authentication app to verify it&apos;s you.
          </p>
        </div>

        <section className={styles.card} aria-label="Two-factor verification">
          <div className={styles.otpRow}>
            {otpDigits.map((digit, index) => (
              <div key={index} className={styles.otpItem}>
                {index === 3 ? (
                  <span className={styles.otpDivider} aria-hidden="true">
                    -
                  </span>
                ) : null}
                <input
                  ref={(el) => {
                    otpInputRefs.current[index] = el;
                  }}
                  className={styles.otpInput}
                  inputMode="numeric"
                  maxLength={1}
                  value={digit}
                  aria-label={`Verification digit ${index + 1}`}
                  onChange={(e) => {
                    const next = e.currentTarget.value.replace(/\D/g, "").slice(-1);
                    setOtpDigits((prev) => {
                      const updated = [...prev];
                      updated[index] = next;
                      return updated;
                    });
                    if (next && index < otpInputRefs.current.length - 1) {
                      otpInputRefs.current[index + 1]?.focus();
                    }
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Backspace" && !otpDigits[index] && index > 0) {
                      otpInputRefs.current[index - 1]?.focus();
                    }
                  }}
                  onPaste={(e) => {
                    const pasted = e.clipboardData.getData("text").replace(/\D/g, "");
                    if (!pasted) return;
                    e.preventDefault();
                    setOtpDigits((prev) => {
                      const updated = [...prev];
                      for (let i = index; i < 6; i += 1) {
                        updated[i] = pasted[i - index] ?? updated[i];
                        if (!pasted[i - index]) break;
                      }
                      return updated;
                    });
                    const lastIndex = Math.min(index + pasted.length - 1, 5);
                    otpInputRefs.current[lastIndex]?.focus();
                  }}
                />
              </div>
            ))}
          </div>

          {error ? (
            <p className={styles.error} role="alert">
              {error}
            </p>
          ) : null}

          <div className={styles.ctaWrap}>
            <Button
              type="button"
              pill
              size="sm"
              className={styles.cta}
              disabled={!canProceed || isProceeding}
              onClick={() => {
                if (!canProceed || isProceeding) return;
                void (async () => {
                  setError("");
                  setIsProceeding(true);
                  try {
                    await api.csrfCookie("/sanctum/csrf-cookie");
                    await api.post("/api/multi-factor-login", {
                      token: resolvedTwoFactorToken,
                      two_factor_code: otpCode,
                    });

                    const authStatus = await api.get<any>("/api/authentication-status");
                    const tenantId = getTenantIdFromAuthenticationStatus(authStatus);
                    if (tenantId === null) {
                      throw new Error("Missing tenant id.");
                    }
                    saveTenantId(tenantId);

                    const dashboardData = await getDashboardData();
                    navigate("/dashboard", { replace: true, state: { dashboardData } });
                  } catch {
                    setError("Invalid code or expired session. Please try again.");
                  } finally {
                    setIsProceeding(false);
                  }
                })();
              }}
            >
              {isProceeding ? "PLEASE WAIT..." : "PROCEED TO DASHBOARD"}
            </Button>
          </div>
        </section>
      </main>
    </div>
  );
}
