import { useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { apiClient } from "../../api/Api";
import { AuthHeader } from "../../components/auth-header/AuthHeader";
import { Button } from "../../components/button/Button";
import { useOnboarding } from "../../app/OnboardingContext";
import { saveTenantId } from "../../lib/session";
import { getDashboardData } from "../../services/dashboardService";
import styles from "./MagicLoginPage.module.css";

type Stage = "email" | "verify";

function getTenantIdFromAuthenticationStatus(data: any): string | number | null {
  if (!data || typeof data !== "object") return null;
  if (data.tenant_id !== undefined && data.tenant_id !== null && String(data.tenant_id).trim() !== "") {
    return data.tenant_id;
  }
  if (data.tenant?.id !== undefined && data.tenant?.id !== null && String(data.tenant.id).trim() !== "") {
    return data.tenant.id;
  }
  if (data.user?.tenant_id !== undefined && data.user?.tenant_id !== null && String(data.user.tenant_id).trim() !== "") {
    return data.user.tenant_id;
  }
  return null;
}

export function MagicLoginPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { reset } = useOnboarding();
  const api = useMemo(() => apiClient, []);
  const prefetchedEmail = (location.state as { email?: string } | null)?.email ?? "";

  const [stage, setStage] = useState<Stage>("email");
  const [email, setEmail] = useState(prefetchedEmail);
  const [otpDigits, setOtpDigits] = useState<string[]>(Array(6).fill(""));
  const [error, setError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isProceeding, setIsProceeding] = useState(false);

  const canContinue = email.trim().length > 0;
  const canProceed = true;

  return (
    <div className={styles.page}>
      <AuthHeader variant="dashboard" userInitial="J" />

      <main className={styles.main}>
        {stage === "email" ? (
          <div className={styles.intro}>
            <h1 className={styles.title}>Welcome back!</h1>
            <p className={styles.subtitle}>
              Enter your register email address to access your Gym Tailor account.
            </p>
          </div>
        ) : stage === "verify" ? (
          <div className={styles.intro}>
            <h1 className={styles.title}>Authenticate to continue</h1>
            <p className={styles.subtitle}>
              Enter a verification code generated by your two-factor authentication app to verify it&apos;s you.
            </p>
          </div>
        ) : null}

        <section className={styles.card} aria-label="Magic login">
          {stage === "email" ? (
            <>
              <div className={styles.fieldWrap}>
                <label className={styles.label} htmlFor="magic-login-email">
                  EMAIL ADDRESS
                </label>
                <input
                  id="magic-login-email"
                  className={styles.input}
                  value={email}
                  onChange={(e) => setEmail(e.currentTarget.value)}
                  placeholder="name@email.com"
                  autoComplete="email"
                />
              </div>

              {error ? (
                <p className={styles.error} role="alert">
                  {error}
                </p>
              ) : null}

              <div className={styles.ctaWrap}>
                <Button
                  type="button"
                  pill
                  size="sm"
                  className={styles.cta}
                  disabled={!canContinue || isSubmitting}
                  onClick={() => {
                    if (!canContinue || isSubmitting) return;
                    void (async () => {
                      setError("");
                      setIsSubmitting(true);
                      try {
                        await api.csrfCookie("/sanctum/csrf-cookie");
                        await api.post("/api/magic-login", {
                          email: email.trim(),
                        });
                        setStage("verify");
                      } catch {
                        setError("Could not continue. Please check the email and try again.");
                      } finally {
                        setIsSubmitting(false);
                      }
                    })();
                  }}
                >
                  {isSubmitting ? "PLEASE WAIT..." : "CONTINUE"}
                </Button>
              </div>
            </>
          ) : (
            <>
              <div className={styles.otpRow}>
                {otpDigits.map((digit, index) => (
                  <div key={index} className={styles.otpItem}>
                    {index === 3 ? (
                      <span className={styles.otpDivider} aria-hidden="true">
                        -
                      </span>
                    ) : null}
                    <input
                      className={styles.otpInput}
                      inputMode="numeric"
                      maxLength={1}
                      value={digit}
                      aria-label={`Verification digit ${index + 1}`}
                      onChange={(e) => {
                        const next = e.currentTarget.value.replace(/\D/g, "").slice(-1);
                        setOtpDigits((prev) => {
                          const updated = [...prev];
                          updated[index] = next;
                          return updated;
                        });
                      }}
                    />
                  </div>
                ))}
              </div>

              {error ? (
                <p className={styles.error} role="alert">
                  {error}
                </p>
              ) : null}

              <div className={styles.ctaWrap}>
                <Button
                  type="button"
                  pill
                  size="sm"
                  className={styles.cta}
                  disabled={!canProceed || isProceeding}
                  onClick={() => {
                    if (!canProceed || isProceeding) return;
                    void (async () => {
                      setError("");
                      setIsProceeding(true);
                      try {
                        const authStatus = await api.get<any>("/api/authentication-status");
                        const tenantId = getTenantIdFromAuthenticationStatus(authStatus);
                        if (tenantId === null) {
                          throw new Error("Missing tenant id.");
                        }
                        saveTenantId(tenantId);

                        const dashboardData = await getDashboardData();
                        reset();
                        navigate("/dashboard", { replace: true, state: { dashboardData } });
                      } catch {
                        setError("Could not proceed to dashboard. Please try again.");
                      } finally {
                        setIsProceeding(false);
                      }
                    })();
                  }}
                >
                  {isProceeding ? "PLEASE WAIT..." : "PROCEED TO DASHBOARD"}
                </Button>
              </div>
            </>
          )}
        </section>
      </main>
    </div>
  );
}
